### ISSUE TITLE
Make get started button on front page more prominent

### ISSUE THREAD

**Issue by mattwelborn** [MolSSI/QCArchiveWebsite#27]
Two suggestions:
1) Increase the size of the Get Started button and change its color to contrast with the blue background.
2) Add an unmissable large Get Started button to the bottom of the front page, potentially replacing the Access QCArchive Now section.

**Comment by dgasmith** [comment]
Sounds good, I can try to adjust the contrast on the Get Started button at the top.

For 2) I think this makes perfect sense. We need to dispatch viewers to the correct location first depending if they wish to view data or generate their own private data.

**Comment by dgasmith** [comment]
Closed by #38.
