### ISSUE TITLE
Clean up Get Started page

### ISSUE THREAD

**Issue by mattwelborn** [MolSSI/QCArchiveWebsite#28]
Currently the Get Started page presents five options:

- View data with QCPortal
- Using the QCArchive ecosystem
- Extend the MolSSI QCArchive database
- Paid Support
- Execute Complex Pipelines

Suggestions:

1. Create more visual separation on the page between the five options. Possible approaches:
    - array the five options linearly top-to-bottom, rather than in a grid
    - add whitespace or a border around each option
    - choose representative images with different color schemes 
2. Consider a narrative presentation. e.g. "I want to..."
    - ... view data in the MolSSI QCArchive.
    - ... add my data to the MolSSI QCArchive.
    - ... compute, store, and organize my own private data locally.
    - ... learn about how the QCArchive ecosystem can be used in my software projects. 
    - .. get enterprise support.

**Comment by mattwelborn** [comment]
Following lunch discussion, I think we should organize the "Get Started" options into two categories: those based on the MolSSI instance and those based on the ecosystem.

**Comment by dgasmith** [comment]
Closed in #41.
