### ISSUE TITLE
Make Use Cases link to examples

### ISSUE THREAD

**Issue by bdice** [MolSSI/QCArchiveWebsite#34]
Hi! I discussed with @dgasmith and wanted to offer a suggestion for the website UX.

I am new to QCArchive. I was perusing the Use Cases page (https://qcarchive.molssi.org/usecases/). I found out later that I was really looking for content that's more like the Examples (e.g. https://docs.qcarchive.molssi.org/en/latest/basic_examples/reaction_datasets.html).

As more examples are written, it might be nice to link the Use Cases to those Examples so that people can connect their research questions / desired workflows to code samples.

**Comment by mattwelborn** [comment]
Use Cases has been demoted to the "Community" menu. Examples remains a top-level link. Does this resolve your issue?

**Comment by bdice** [comment]
@mattwelborn Yes, I think so! Thanks for the update. 😄

**Comment by bdice** [comment]
@mattwelborn One more thing that I just saw with the new structure: The new Examples page is in an iframe and I can't copy links to specific pages -- if I click on menus in the ReadTheDocs-hosted content, it still shows "https://qcarchive.molssi.org/examples/" in the URL bar because the examples are in that frame. Seems like sending the user directly to ReadTheDocs would be preferable, but that's a separate issue.

**Comment by mattwelborn** [comment]
Thanks for bringing this up. #73
