### ISSUE TITLE
Answers to the Slack questions

### ISSUE THREAD

**Issue by SinaMostafanejad** [MolSSI/QCArchiveWebsite#36]
1) Quantum Chemistry Archive is a user friendly database of quantum chemical results for both analysis and generating new data.
2) It can be thought of a central server for making the quantum molecular science data available to the public free of charge. However, it also provides the community with the tools to analyze or generate new results from it.
3) It can be done through github or as a user, installing the environment through conda with jupyter or similar means.

**Comment by dgasmith** [comment]
Thanks @SinaMostafanejad! We recorded these in another google doc, closing this now.
