### ISSUE TITLE
http and https point to different infrastructure pages

### ISSUE THREAD

**Issue by mattwelborn** [MolSSI/QCArchiveWebsite#43]
This might be a cache issue on my machine, but:

http://docs.qcarchive.molssi.org/en/latest/ goes to the QCArchive Infrastructure page.
https://docs.qcarchive.molssi.org/en/latest/ goes to the QCArchve Examples page.

**Comment by dgasmith** [comment]
Both link correctly for me, may be worth blowing away your cache and retrying.

**Comment by mattwelborn** [comment]
Yep, problem was on my end.
